package ar.edu.unlam.pb2.interfaz;

public enum MenuPrincipal {

	CONSULTAR_SI_LA_SALA_ESTA_VACIA, CONSULTAR_SI_LA_BUTACA_ESPECIFICA_ESTA_VACIA, OCUPAR_BUTACA,
	CONSULTAR_CANTIDAD_DE_BUTACAS_OCUPADAS, CONSULTAR_CANTIDAD_BUTACAS_VACIAS,
	CONSULTAR_SI_SE_PUEDE_ACOMODAR_GRUPO_CONTINUO, VER_SALA_DE_CINE,SALIR

}
